apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: event-listener
spec:
  serviceAccountName: pipeline
  triggers:
    - name: git-clone-trigger
      binding:
        ref: trigger-binding
      template:
        ref: trigger-template
