apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone-task
spec:
  params:
    - name: repository-url
      type: string
      description: The URL of the Git repository to clone
    - name: revision
      type: string
      description: The Git revision (branch, tag, commit SHA) to checkout
      default: "master"
  workspaces:
    - name: output
      description: The workspace where the Git repository will be cloned
  steps:
    - name: clone
      image: "alpine/git:v2.30.2"  # Git image to perform clone operation
      script: |
        git clone $(params.repository-url) $(workspaces.output.path) --branch $(params.revision)
    
    - name: install-dependencies
      image: "ubuntu:22.04"
      script: |
        apt-get update && apt-get install -y \
          build-essential \
          cmake \
          clang \
          libc++-dev \
          libgflags-dev \
          liblz4-dev \
          zlib1g-dev \
          libboost-all-dev \
          libssl-dev \
          liblzma-dev \
          && apt-get clean
        
    - name: build
      image: "ubuntu:22.04"
      script: |
        cd /workspace/output
        mkdir build
        cd build
        cmake ..
        cmake --build . --target clickhouse
