apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-clickhouse
spec:
  workspaces:
    - name: output
      description: The git repo will be cloned onto the volume backing this workspace
      mountPath: /artifacts
  tasks:
    - name: install-prerequisites
      taskSpec:
        steps:
          - name: install
            image: ubuntu:20.04
            script: |
              apt-get update
              apt-get install -y git cmake ccache clang ninja-build
    - name: clone-repo
      taskSpec:
        steps:
          - name: clone
            image: alpine/git
            script: |
              git clone https://github.com/ClickHouse/ClickHouse.git
            workspaces:
              - name: output
                description: The git repo will be cloned onto the volume backing this workspace
                mountPath: /artifacts
    - name: build-clickhouse
      runAfter:
        - install-prerequisites
        - clone-repo
      taskSpec:
        workspaces:
          - name: output
            description: The git repo will be cloned onto the volume backing this workspace
            mountPath: /artifacts
        steps:
          - name: build
            image: cmake:latest
            script: |
              cd ClickHouse
              mkdir build
              cd build
              cmake ..
            workspaces:
              - name: output
                description: The git repo will be cloned onto the volume backing this workspace
                mountPath: /artifacts
