apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: clone-clickhouse
spec:
  steps:
    - name: clone
      image: alpine/git
      script: |
        #!/bin/sh
        git clone https://github.com/shivanim05/ClickHouse_updated.git
  workspaces:
    - name: output
